AWSTemplateFormatVersion: '2010-09-09'
Description: Laravel ECS on Fargate Deployment

Parameters:
  DeployTime:
    Type: String
    Default: "0"  # run.shから現在時刻を渡す

# ------------------------------------------------------------
# リソース
# ------------------------------------------------------------
Resources:
  # --------------------------
  # ECS セキュリティグループ
  # --------------------------
  ECSSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: Security group for Laravel ECS service
      VpcId:
        Fn::ImportValue: laravel-network-stack-VpcId
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: 8000
          ToPort: 8000
          CidrIp: 0.0.0.0/0
      SecurityGroupEgress:
        - IpProtocol: -1
          FromPort: -1
          ToPort: -1
          CidrIp: 0.0.0.0/0

  # --------------------------
  # ECS クラスタ
  # --------------------------
  ECSCluster:
    Type: AWS::ECS::Cluster
    Properties:
      ClusterName: laravel-ecs-cluster

  # --------------------------
  # ECS タスク実行ロール
  # --------------------------
  TaskExecutionRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: laravel-task-execution-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/CloudWatchLogsFullAccess
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore

  # タスクロール（コンテナ実行時の権限）を追加
  TaskRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: laravel-task-role
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: ecs-tasks.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/service-role/AmazonECSTaskExecutionRolePolicy
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore  # SSM接続用の権限を追加
      Policies:
        - PolicyName: TaskPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - ecr:GetAuthorizationToken
                  - ecr:BatchCheckLayerAvailability
                  - ecr:GetDownloadUrlForLayer
                  - ecr:BatchGetImage
                  - ssmmessages:CreateControlChannel    # SSM接続用の権限を追加
                  - ssmmessages:CreateDataChannel       # SSM接続用の権限を追加
                  - ssmmessages:OpenControlChannel      # SSM接続用の権限を追加
                  - ssmmessages:OpenDataChannel         # SSM接続用の権限を追加
                Resource: '*'

  # --------------------------
  # ECS タスク定義
  # --------------------------
  ECSTaskDefinition:
    Type: AWS::ECS::TaskDefinition
    Properties:
      Family: laravel-task
      Cpu: '256'
      Memory: '512'
      NetworkMode: awsvpc
      RequiresCompatibilities:
        - FARGATE
      ExecutionRoleArn: !GetAtt TaskExecutionRole.Arn
      TaskRoleArn: !GetAtt TaskRole.Arn
      ContainerDefinitions:
        - Name: laravel-app
          Image: !Sub
            - ${RepoUri}:latest
            - RepoUri: !ImportValue laravel-network-stack-ECRRepositoryUri
          PortMappings:
            - ContainerPort: 8000
              Protocol: tcp
          Essential: true
          HealthCheck:
            Command:
              - CMD-SHELL
              - php artisan --version || exit 1
            Interval: 30
            Timeout: 5
            Retries: 3
            StartPeriod: 30
          Environment:
            - Name: APP_ENV
              Value: production
            - Name: APP_DEBUG
              Value: "true"
            - Name: APP_KEY
              Value: "base64:OVWmZZ6xK9tUr1/nGHxw2tW6fIMUOXw5PpNdgpZdXO0="
            - Name: IMAGE_UPDATE_TIME
              Value: !Ref DeployTime
          LogConfiguration:
            LogDriver: awslogs
            Options:
              awslogs-group: "/ecs/laravel-app"
              awslogs-region: !Ref AWS::Region
              awslogs-stream-prefix: ecs
          WorkingDirectory: /var/www
          Command:
            - "php"
            - "artisan"
            - "serve"
            - "--host=0.0.0.0"
            - "--port=8000"

  # --------------------------
  # ECS サービス
  # --------------------------
  ECSService:
    Type: AWS::ECS::Service
    DependsOn:
      - LogGroup
      - ECSCluster
    Properties:
      ServiceName: laravel-service
      Cluster: !Ref ECSCluster
      TaskDefinition: !Ref ECSTaskDefinition
      DesiredCount: 1
      LaunchType: FARGATE
      PlatformVersion: LATEST
      NetworkConfiguration:
        AwsvpcConfiguration:
          Subnets:
            - Fn::ImportValue: laravel-network-stack-SubnetIds
          SecurityGroups:
            - !Ref ECSSecurityGroup
          AssignPublicIp: ENABLED
      HealthCheckGracePeriodSeconds: 120
      EnableExecuteCommand: true
      DeploymentConfiguration:
        MaximumPercent: 200
        MinimumHealthyPercent: 100
      PropagateTags: SERVICE

  # --------------------------
  # CloudWatch Logs
  # --------------------------
  LogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: /ecs/laravel-app
      RetentionInDays: 7

Outputs:
  ECSClusterName:
    Description: ECS Cluster Name
    Value: !Ref ECSCluster
    Export:
      Name: !Sub ${AWS::StackName}-ECSClusterName